services:
  - type: web
    name: attendanceapp
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    envVars:
      - key: DB_HOST
        value: ""
      - key: DB_NAME
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASS
        value: ""
      - key: DB_PORT
        value: "11891"
    healthCheckPath: /status.php
